---
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/npm', '.']
# storing storj API key in file
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ["-c","gcloud secrets versions access latest --secret=StorjAPIKey >>./dist/secret.txt" ]
# running npm install command
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'npm'
    args: ["install"]
# building module using node-gyp module
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'bash'
    args: ["-c","make && node-gyp configure && node-gyp rebuild"]
# install typescript
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'bash'
    args: ["-c","npm install -g typescript && tsc && tsc ./test/testcase.ts"]
# running testcases
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'npm'
    args: ["test"]
tags: ['cloud-builders-community']
images: ['gcr.io/$PROJECT_ID/npm']
tags: ['cloud-builders-community']
